spring:
    cloud:
        config:
            server:
                encrypt:
                  enabled: false
                git:
                  uri: https://github.com/iloveZzz/spring-config-repo
                  search-paths: app-server,web-client,yml-ceshi
                health:
                  repositories:
                    app-server:
                      label: master
                      name: microserver-app
                      profiles: dev,product
        bus:
          trace:
            enabled: true

    application:
      name: microservice-config-server
    rabbitmq:
      host: 192.168.129.201
      port: 5672
      addresses: 192.168.129.201:5672
      username: xianbei
      password: Xianbei123.
      virtual-host: test_config
management:
  security:
    enabled: false
server:
  port: 8080
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.129.201:5001/eureka/
  instance:
    preferIpAddress: true


