spring:
    cloud:
        config:
            server:
                encrypt:
                  enabled: false
                git:
                  uri: https://github.com/iloveZzz/spring-config-repo
                  search-paths: app-server,web-client,yml-ceshi
                health:
                  repositories:
                    app-server:
                      label: master
                      name: microserver-app
                      profiles: dev,product

    application:
      name: microservice-config-server
management:
  security:
    enabled: true
server:
  port: 8080
logging:
  level:
    org.springframework.cloud: INFO
    org.springframework.boot: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: http://xianbei.viphk.ngrok.org/eureka/
  instance:
    preferIpAddress: true


