spring:
    cloud:
        config:
            server:
                git:
                  uri: https://github.com/iloveZzz/spring-config-repo
    application:
      name: microservice-config-server
management:
  security:
    enabled: false
server:
  port: 8080

